# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600c641a0dd1861f806e3a2c2e9c6e5ad6aa286a362ddce99f7fd4713966cb93519891c8dec8e4900d7d1215f30c08b2a8efef6b53ffef611a14da12892f023c

test:
  secret_key_base: 091d98b7a9ee8fc285c5fc4d5c5028fd1eeb3cb91e8ff4bf3e8b3de0b0f2b9f3baf9341b0034210895d68366efe5c6b89e09e26a54d9076ce67eea2a50605356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
